---
title: 'HW_08_8.1_hclust: hclust cluster methodology on breast-cancer-wisconsin dataset'
author: 'Daksh Bhuva | CWID: 10475468'
date: "11/22/2021"
output:
  pdf_document: default
  html_document: default
---
### Preparing the dataset
```{r}
# Loading the dataset and convert '?' into NA 
data = read.csv("/Users/dakshbhuva/Desktop/CS-513 KDD/wisc_bc_ContinuousVar.csv", na.strings = "?")

# Remove the missing values
data<- na.omit(data)

# Removing the column 'id' as it is not required
data<-data[-1]
```

### Implementing hclust methodology
```{r}
# Distance Matrix Computation
bcw_dist <- dist(data[,-1])
# Hierarchical Clustering
hclust_resutls<-hclust(bcw_dist)
```

### Plotting the results
```{r}
plot(hclust_resutls)
```

### Cutting the Tree into 2 Clusters
```{r}
hclust_2<-cutree(hclust_resutls,2)
```

### Frequency table for predictions
```{r}
table(hclust_2,data[,1])
```

### Package to plot the clusters
```{r}
library(fpc)
```

### Plotting the clusters
```{r}
plotcluster(data[,-1], hclust_2)
```