---
title: 'HW_07_ANN: ANN Methodology with five (5) nodes in the hidden layer on breast-cancer-wisconsin
  dataset'
author: 'Daksh Bhuva | CWID: 10475468'
date: "11/15/2021"
output:
  pdf_document: default
  html_document: default
---
### Preparing the dataset
```{r}
# Loading the dataset and convert '?' into NA 
data = read.csv("/Users/dakshbhuva/Desktop/CS-513 KDD/wisc_bc_ContinuousVar.csv", na.strings = "?")

# Factoring the dataset
data$diagnosis <-factor(data$diagnosis)

# Removing the missing values
data<-data.frame(lapply(na.omit(data),as.numeric))

# Removing the column 'id' as it is not required
data<-data[-1]
```

### Normalizing the data
```{r}
df <- as.data.frame(apply(data[,1:ncol(data)],2,function(x) (x - min(x))/(max(x)-min(x))))
```

### Splitting the normalized dataset into training and test data
```{r}
idx<-sort(sample(nrow(df),as.integer(.70*nrow(df))))

training<-df[idx,]
test<-df[-idx,]
```

### Installing package to implement ANN methodology
```{r}
#install.packages("neuralnet")
#?neuralnet()
library("neuralnet")
```

### Implementing ANN methodology with five (5) nodes in the hidden layer
```{r}
model<- neuralnet( diagnosis~., training, hidden=5, exclude = NULL, threshold=0.01)
pred<- predict(model, test)
```

### Plotting the model
```{r}
plot(model)
```

### Discretizing the predicted values into '0' and '1'
```{r}
pred_dis <- ifelse(pred<0.5,0,1)
```

### Frequency table for predictions
```{r}
table(Actual = test$diagnosis, Prediction = pred_dis)
```

### Calculating the error rate
```{r}
# Number of wrong predictions
wrong<- (test$diagnosis!=pred_dis)
# Error Rate in prediction of ANN
error_rate<-sum(wrong)/length(test$diagnosis)

print(paste("Error Rate:" , error_rate))
```